#!/bin/bash

app='rainloop'	# This could never work with multi-instance. Need to find a better way
domain=$1
rainloop_path=/var/www/$app/app

echo '
imap_host = "localhost"
imap_port = 993
imap_secure = "SSL"
imap_short_login = On
sieve_use = On
sieve_allow_raw = On
sieve_host = "localhost"
sieve_port = 4190
sieve_secure = "TLS"
smtp_host = "localhost"
smtp_port = 587
smtp_secure = "TLS"
smtp_short_login = On
smtp_auth = On
smtp_php_mail = Off
white_list = ""
' | sudo tee --append $rainloop_path/data/_data_/_default_/domains/$domain.ini > /dev/null
