#!/bin/bash

app='rainloop'	# This could never work with multi-instance. Need to find a better way
domain=$1
rainloop_path=/var/www/$app/app

sudo cp ../conf/data/domains/domain.tld.ini $rainloop_path/data/_data_/_default_/domains/$domain.ini
