#!/bin/bash

# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/rainloop
mkdir -p $backup_dir

sudo cp -a /var/www/rainloop/. $backup_dir/sources
sudo cp -a /etc/php5/fpm/pool.d/rainloop.conf $backup_dir/php-fpm.conf

db_pwd=$(sudo yunohost app setting rainloop mysqlpwd)
sudo mysqldump -u rainloop -p"$db_pwd" rainloop > $backup_dir/dump.sql

# Copy Nginx and YunoHost parameters to make the script "standalone"
sudo cp -a /etc/yunohost/apps/rainloop/. $backup_dir/yunohost
domain=$(sudo yunohost app setting rainloop domain)
sudo cp -a /etc/nginx/conf.d/$domain.d/rainloop.conf $backup_dir/nginx.conf
