#!/bin/bash

# Exit on command errors and treat unset variables as an error
	set -eu
	app=$YNH_APP_INSTANCE_NAME

# Set app specific variables
	dbname=$app
	dbuser=$app

# Source app helpers
	. /usr/share/yunohost/helpers

# Retrieve app settings
	domain=$(ynh_app_setting_get "$app" domain)
	path=$(ynh_app_setting_get "$app" path)
	dbpass=$(ynh_app_setting_get "$app" mysqlpwd)

# Copy the app files
	DESTDIR="/var/www/$app"
	ynh_backup "$DESTDIR" "sources"

# Copy the conf files
	ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"
	
# Copy dedicated php-fpm process to backup folder
        ynh_backup "/etc/php5/fpm/pool.d/$app.conf" "php-fpm.conf"

# Dump the database
	mysqldump -u "$dbuser" -p"$dbpass" --no-create-db "$dbname" > ./dump.sql
	ynh_backup "./dump.sql" "dump.sql"
