#!/bin/bash

# Exit on command errors and treat unset variables as an error
	set -eu
	app=$YNH_APP_INSTANCE_NAME

# Source app helpers
	source /usr/share/yunohost/helpers

# Retrieve arguments
	dbuser=$app
	dbname=$app
	domain=$(ynh_app_setting_get "$app" domain)

# Drop MySQL database and user
	ynh_mysql_drop_db "$dbname" 2>&1 || true
	ynh_mysql_drop_user "$dbuser" 2>&1 || true

# Delete app directory and configurations
	sudo rm -rf "/var/www/${app}"
	sudo rm -f "/etc/php5/fpm/pool.d/${app}.conf"
	[[ -n $domain ]] && sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Remove GPG key
	sudo gpg --batch --delete-key --yes Rainloop

# Reload services
	sudo service php5-fpm reload || true
	sudo service nginx reload || true
