#!/bin/bash

app=rainloop

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
is_public=$(sudo yunohost app setting $app is_public)


# Check domain/path availability
#sudo yunohost app checkurl $domain$path -a rainloop
#if [[ ! $? -eq 0 ]]; then
#    exit 1
#fi

# Generate random DES key & password
#deskey=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
#db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'rainloop' as database name and user
#db_user=rainloop

# Initialize database and store mysql password for upgrade
#sudo yunohost app initdb $db_user -p $db_pwd -s $(readlink -e ../sources/SQL/mysql.initial.sql)
#sudo yunohost app setting rainloop mysqlpwd -v $db_pwd

#mysql -u $db_user -p$db_pwd $db_user < ../sources/plugins/automatic_addressbook/SQL/mysql.initial.sql

# Copy files to the right place
final_path=/var/www/$app/rainloop/v/
sudo rm -rf $final_path/*
#sudo mkdir -p $final_path
sudo cp -a ../sources/rainloop/v/* $final_path


# Set permissions to rainloop directory
# sudo mkdir -p $final_path/logs
sudo chown -R www-data:www-data $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/rainloop.conf

sed -i "s@NAMETOCHANGE@rainloop@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/rainloop.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

# Make app public if necessary
sudo yunohost app setting my_webapp is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting my_webapp skipped_uris -v "/"
fi


# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm reload
sudo service nginx reload
sudo yunohost app ssowatconf
